### ISSUE TITLE
No issue: add another control point

### ISSUE THREAD

**Issue by 7890** [nadeemelahi/tweaning#1]
Hi
Would it be feasable to add another control point?
```
return this.AY*t*t*t + this.BY*t*t + this.CY*t + this.y0;
->
return this.AY*t*t*t*t + this.BY*t*t*t + this.CY*t*t + this.DY*t + this.y0;
```
I'm struggling with the math to calculate the coefficients.

**Comment by nadeemelahi** [comment]
I didn't derive those equations. I just looked them up. They are the same equations everyone is using for tweaning. If you want to understand the math https://javascript.info/bezier-curve

**Comment by 7890** [comment]
Thanks, this is an exellent page! 
Using this formula for 5 points seems to work:
```
P=    t^4 * (1 - t)^0 * A  
+ 4 * t^3 * (1 - t)^1 * B 
+ 6 * t^2 * (1 - t)^2 * C
+ 4 * t^1 * (1 - t)^3 * D
+     t^0 * (1 - t)^4 * E

(^0 for clairty, ==1)
```
However your implementation in tweaning.js seems smarter (doing less calculations by keeping the coefficients?) and I don't see how it would translate to calculating AX, AY, .. e.g. I can't find any (1 - t) in tweaning.js..
Thanks

**Comment by 7890** [comment]
Btw this is what I tried, with additional cx2, cy2, DX, DY:
```
this.DX = 4 * (cx0 -  x0);
this.DY = 4 * (cy0 -  y0);

this.CX = 4 * (cx1 - cx0) - this.DX;
this.CY = 4 * (cy1 - cy0) - this.DY;

this.BX = 4 * (cx2 - cx1) - this.DX  - this.CX;
this.BY = 4 * (cy2 - cy1) - this.DY  - this.CY;

this.AX = x1 - x0 - this.DX - this.CX - this.BX;
this.AY = y1 - y0 - this.DY - this.CY - this.BY;

this.x0=x0;
this.y0=y0;
```
It almost works, there's still a thinko.
